### ISSUE TITLE
Int Type Mismatch

### ISSUE THREAD

**Issue by acenko** [PJ-Watson/sep-pjw#2]
In some cases (seen on Windows 10 x86-64), the dtype of the "flag" entry in the result array is incorrect. The code specifies np.int_
https://github.com/PJ-Watson/sep-pjw/blob/79cc2a4105eb52ef82be73d4af073f00df60439f/sep_pjw.pyx#L810
which on this system is np.int64 instead of np.int32. Explicitly defining "np.int_ = np.int32" before using sep_pjw works. Likely using np.int32 instead of np.int_ for the "flag" entry would work on all systems.

Test cases:
```
import sep_pjw as sep
import numpy as np
img = np.zeros((1000, 1000))
sep.extract(img, 10)
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 4
      2 import numpy as np
      3 img = np.zeros((1000, 1000))
----> 4 sep.extract(img, 10)

File sep_pjw.pyx:780, in sep_pjw.extract()

ValueError: Buffer dtype mismatch, expected 'long' but got 'long long' in 'Object.flag'
```

```
import sep_pjw as sep
import numpy as np
np.int_ = np.int32
img = np.zeros((1000, 1000))
sep.extract(img, 10)
```
```
array([],
      dtype=[('thresh', '<f8'), ('npix', '<i8'), ('tnpix', '<i8'), ('xmin', '<i8'), ('xmax', '<i8'), ('ymin', '<i8'), ('ymax', '<i8'), ('x', '<f8'), ('y', '<f8'), ('x2', '<f8'), ('y2', '<f8'), ('xy', '<f8'), ('errx2', '<f8'), ('erry2', '<f8'), ('errxy', '<f8'), ('a', '<f8'), ('b', '<f8'), ('theta', '<f8'), ('cxx', '<f8'), ('cyy', '<f8'), ('cxy', '<f8'), ('cflux', '<f8'), ('flux', '<f8'), ('cpeak', '<f8'), ('peak', '<f8'), ('xcpeak', '<i8'), ('ycpeak', '<i8'), ('xpeak', '<i8'), ('ypeak', '<i8'), ('flag', '<i4')])
```

**Comment by PJ-Watson** [comment]
Hi @acenko, many thanks for letting me know about this, and for the detailed debugging! It looks like the issue was introduced in 1b49dad1010d679b79ef2b1b019b83d0fc16efe1 , and wasn't caught because the tests only ran on Ubuntu. Compared to the other parts of the code which return a flag (and the C API), the correct return type should have been `np.short`.

I'm closing the issue for now as it should be fixed in [v1.3.6 ](https://github.com/PJ-Watson/sep-pjw/releases/tag/v1.3.6), but if there are any other problems on Windows, feel free to reopen this.
